apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: venturplex-devops-example
spec:
  selector:
    app: data-pipeline
    version: v1
  ports:
    - protocol: TCP
      port: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-pipeline
  namespace: venturplex-devops-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-pipeline
  template:
    metadata:
      labels:
        app: data-pipeline
        version: v1
    spec:
      hostAliases:
        - ip: "127.0.0.1"
          hostnames:
            - "postgres"
      containers:
        - name: postgres
          env:
            - name: POSTGRES_DB
              value: public
            - name: POSTGRES_USER
              value: root
          image: postgres:9.4
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: db-data
          emptyDir: {}
