apiVersion: v1
kind: Service
metadata:
  name: server-release
  namespace: venturplex-devops-example
spec:
  type: LoadBalancer
  selector:
    app: server-release
  ports:
    - protocol: TCP
      targetPort: api
      port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-release
  namespace: venturplex-devops-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-release
  template:
    metadata:
      labels:
        app: server-release
        version: v1
    spec:
      containers:
        - name: server-release
          image: venturplex/server-release:latest
          ports:
            - name: api
              containerPort: 8080
